name: renovate-config-validator

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1